### ISSUE TITLE
Updating textarea text after init...

### ISSUE THREAD

**Issue by TK11703** [brandonaaron/jquery-expandable#5]
Brandon,

Great contribution so far. I have used a few other plugins, and I find your solution elegant and simple. However here is a issue I ran into. In IE10, I am loading the page and calling $("textarea").expandable(). Then I make an ajax call and get a new text value for the textarea. When I update the textarea value through javascript, the textarea is not growing/shrinking to reflect the new text size. 

I can get around this by just calling $("textarea").expandable() again after I assign the new value. However, isn't this going to create a new mirror element to use instead of reusing the existing mirror element? To get around this, can we have access to an update function?

I added this line right after the if(options.init) check();
$this.bind('update', check);

So then I can do this...
$("textarea").expandable()
//wait a while...ajax call, whatever...
$("textarea").val("some new text").trigger("update");

**Comment by brandonaaron** [comment]
Good idea. Implemented in 1.1.4.

**Comment by TK11703** [comment]
Awesome, glad I could help.
